<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420121343 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ligne_panier_menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT DEFAULT 1 NOT NULL, prix_unitaire NUMERIC(6, 2) NOT NULL, panier_id INT NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA06DFDDF77D927C ON ligne_panier_menu (panier_id)');
        $this->addSql('CREATE INDEX IDX_EA06DFDDCCD7E912 ON ligne_panier_menu (menu_id)');
        $this->addSql('CREATE TABLE ligne_panier_menu_detail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ligne_panier_menu_id INT NOT NULL, composant_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C8CB0093CD31F5C ON ligne_panier_menu_detail (ligne_panier_menu_id)');
        $this->addSql('CREATE INDEX IDX_C8CB00937F3310E7 ON ligne_panier_menu_detail (composant_id)');
        $this->addSql('CREATE INDEX IDX_C8CB0093F347EFB ON ligne_panier_menu_detail (produit_id)');
        $this->addSql('CREATE TABLE ligne_panier_menu_detail_option (ligne_panier_menu_detail_id INT NOT NULL, option_id INT NOT NULL, PRIMARY KEY (ligne_panier_menu_detail_id, option_id))');
        $this->addSql('CREATE INDEX IDX_50A994B195A2D869 ON ligne_panier_menu_detail_option (ligne_panier_menu_detail_id)');
        $this->addSql('CREATE INDEX IDX_50A994B1A7C41D6F ON ligne_panier_menu_detail_option (option_id)');
        $this->addSql('CREATE TABLE menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, prix NUMERIC(6, 2) NOT NULL, image_url VARCHAR(255) DEFAULT NULL, disponible BOOLEAN DEFAULT true NOT NULL, position INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE menu_composant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, position INT DEFAULT 0 NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5C4E1FDCCD7E912 ON menu_composant (menu_id)');
        $this->addSql('CREATE TABLE menu_composant_produit (menu_composant_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (menu_composant_id, produit_id))');
        $this->addSql('CREATE INDEX IDX_96F922ED31E142 ON menu_composant_produit (menu_composant_id)');
        $this->addSql('CREATE INDEX IDX_96F922EDF347EFB ON menu_composant_produit (produit_id)');
        $this->addSql('ALTER TABLE ligne_panier_menu ADD CONSTRAINT FK_EA06DFDDF77D927C FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier_menu ADD CONSTRAINT FK_EA06DFDDCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail ADD CONSTRAINT FK_C8CB0093CD31F5C FOREIGN KEY (ligne_panier_menu_id) REFERENCES ligne_panier_menu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail ADD CONSTRAINT FK_C8CB00937F3310E7 FOREIGN KEY (composant_id) REFERENCES menu_composant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail ADD CONSTRAINT FK_C8CB0093F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail_option ADD CONSTRAINT FK_50A994B195A2D869 FOREIGN KEY (ligne_panier_menu_detail_id) REFERENCES ligne_panier_menu_detail (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail_option ADD CONSTRAINT FK_50A994B1A7C41D6F FOREIGN KEY (option_id) REFERENCES option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_composant ADD CONSTRAINT FK_F5C4E1FDCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_composant_produit ADD CONSTRAINT FK_96F922ED31E142 FOREIGN KEY (menu_composant_id) REFERENCES menu_composant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_composant_produit ADD CONSTRAINT FK_96F922EDF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ligne_panier_menu DROP CONSTRAINT FK_EA06DFDDF77D927C');
        $this->addSql('ALTER TABLE ligne_panier_menu DROP CONSTRAINT FK_EA06DFDDCCD7E912');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail DROP CONSTRAINT FK_C8CB0093CD31F5C');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail DROP CONSTRAINT FK_C8CB00937F3310E7');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail DROP CONSTRAINT FK_C8CB0093F347EFB');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail_option DROP CONSTRAINT FK_50A994B195A2D869');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail_option DROP CONSTRAINT FK_50A994B1A7C41D6F');
        $this->addSql('ALTER TABLE menu_composant DROP CONSTRAINT FK_F5C4E1FDCCD7E912');
        $this->addSql('ALTER TABLE menu_composant_produit DROP CONSTRAINT FK_96F922ED31E142');
        $this->addSql('ALTER TABLE menu_composant_produit DROP CONSTRAINT FK_96F922EDF347EFB');
        $this->addSql('DROP TABLE ligne_panier_menu');
        $this->addSql('DROP TABLE ligne_panier_menu_detail');
        $this->addSql('DROP TABLE ligne_panier_menu_detail_option');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE menu_composant');
        $this->addSql('DROP TABLE menu_composant_produit');
    }
}
