<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420130010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE menu_personnalise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) DEFAULT NULL, session_id VARCHAR(128) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE menu_personnalise_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, menu_personnalise_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7DDB732DA012D9C1 ON menu_personnalise_ligne (menu_personnalise_id)');
        $this->addSql('CREATE INDEX IDX_7DDB732DF347EFB ON menu_personnalise_ligne (produit_id)');
        $this->addSql('CREATE TABLE menu_perso_ligne_option (menu_personnalise_ligne_id INT NOT NULL, option_id INT NOT NULL, PRIMARY KEY (menu_personnalise_ligne_id, option_id))');
        $this->addSql('CREATE INDEX IDX_5CC45B7C43C73197 ON menu_perso_ligne_option (menu_personnalise_ligne_id)');
        $this->addSql('CREATE INDEX IDX_5CC45B7CA7C41D6F ON menu_perso_ligne_option (option_id)');
        $this->addSql('ALTER TABLE menu_personnalise_ligne ADD CONSTRAINT FK_7DDB732DA012D9C1 FOREIGN KEY (menu_personnalise_id) REFERENCES menu_personnalise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_personnalise_ligne ADD CONSTRAINT FK_7DDB732DF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_perso_ligne_option ADD CONSTRAINT FK_5CC45B7C43C73197 FOREIGN KEY (menu_personnalise_ligne_id) REFERENCES menu_personnalise_ligne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_perso_ligne_option ADD CONSTRAINT FK_5CC45B7CA7C41D6F FOREIGN KEY (option_id) REFERENCES option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_composant_produit DROP CONSTRAINT fk_96f922edf347efb');
        $this->addSql('ALTER TABLE menu_composant_produit DROP CONSTRAINT fk_96f922ed31e142');
        $this->addSql('DROP TABLE menu_composant_produit');
        $this->addSql('ALTER TABLE ligne_panier_menu ALTER menu_id DROP NOT NULL');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail ALTER composant_id DROP NOT NULL');
        $this->addSql('ALTER TABLE menu_composant ADD categorie_id INT NOT NULL');
        $this->addSql('ALTER TABLE menu_composant ADD CONSTRAINT FK_F5C4E1FDBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F5C4E1FDBCF5E72D ON menu_composant (categorie_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE menu_composant_produit (menu_composant_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (menu_composant_id, produit_id))');
        $this->addSql('CREATE INDEX idx_96f922edf347efb ON menu_composant_produit (produit_id)');
        $this->addSql('CREATE INDEX idx_96f922ed31e142 ON menu_composant_produit (menu_composant_id)');
        $this->addSql('ALTER TABLE menu_composant_produit ADD CONSTRAINT fk_96f922edf347efb FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu_composant_produit ADD CONSTRAINT fk_96f922ed31e142 FOREIGN KEY (menu_composant_id) REFERENCES menu_composant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu_personnalise_ligne DROP CONSTRAINT FK_7DDB732DA012D9C1');
        $this->addSql('ALTER TABLE menu_personnalise_ligne DROP CONSTRAINT FK_7DDB732DF347EFB');
        $this->addSql('ALTER TABLE menu_perso_ligne_option DROP CONSTRAINT FK_5CC45B7C43C73197');
        $this->addSql('ALTER TABLE menu_perso_ligne_option DROP CONSTRAINT FK_5CC45B7CA7C41D6F');
        $this->addSql('DROP TABLE menu_personnalise');
        $this->addSql('DROP TABLE menu_personnalise_ligne');
        $this->addSql('DROP TABLE menu_perso_ligne_option');
        $this->addSql('ALTER TABLE ligne_panier_menu ALTER menu_id SET NOT NULL');
        $this->addSql('ALTER TABLE ligne_panier_menu_detail ALTER composant_id SET NOT NULL');
        $this->addSql('ALTER TABLE menu_composant DROP CONSTRAINT FK_F5C4E1FDBCF5E72D');
        $this->addSql('DROP INDEX IDX_F5C4E1FDBCF5E72D');
        $this->addSql('ALTER TABLE menu_composant DROP categorie_id');
    }
}
