<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419190226 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(20) NOT NULL, total NUMERIC(8, 2) NOT NULL, statut VARCHAR(30) DEFAULT \'en_attente\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaire TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6EEAA67DF55AE19E ON commande (numero)');
        $this->addSql('CREATE TABLE ligne_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire NUMERIC(6, 2) NOT NULL, nom_produit VARCHAR(150) NOT NULL, options_choisies JSON DEFAULT NULL, commande_id INT NOT NULL, produit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3170B74B82EA2E54 ON ligne_commande (commande_id)');
        $this->addSql('CREATE INDEX IDX_3170B74BF347EFB ON ligne_commande (produit_id)');
        $this->addSql('CREATE TABLE ligne_panier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT DEFAULT 1 NOT NULL, prix_unitaire NUMERIC(6, 2) NOT NULL, panier_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_21691B4F77D927C ON ligne_panier (panier_id)');
        $this->addSql('CREATE INDEX IDX_21691B4F347EFB ON ligne_panier (produit_id)');
        $this->addSql('CREATE TABLE ligne_panier_option (ligne_panier_id INT NOT NULL, option_id INT NOT NULL, PRIMARY KEY (ligne_panier_id, option_id))');
        $this->addSql('CREATE INDEX IDX_E41CE3CF38989DF4 ON ligne_panier_option (ligne_panier_id)');
        $this->addSql('CREATE INDEX IDX_E41CE3CFA7C41D6F ON ligne_panier_option (option_id)');
        $this->addSql('CREATE TABLE option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, prix_supplementaire NUMERIC(5, 2) DEFAULT \'0.00\' NOT NULL, type VARCHAR(20) NOT NULL, disponible BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE panier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id VARCHAR(128) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24CC0DF2613FECDF ON panier (session_id)');
        $this->addSql('CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, prix NUMERIC(6, 2) NOT NULL, image_url VARCHAR(255) DEFAULT NULL, disponible BOOLEAN DEFAULT true NOT NULL, position INT DEFAULT 0 NOT NULL, categorie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_29A5EC27BCF5E72D ON produit (categorie_id)');
        $this->addSql('CREATE TABLE produit_option (produit_id INT NOT NULL, option_id INT NOT NULL, PRIMARY KEY (produit_id, option_id))');
        $this->addSql('CREATE INDEX IDX_ADD4CB8AF347EFB ON produit_option (produit_id)');
        $this->addSql('CREATE INDEX IDX_ADD4CB8AA7C41D6F ON produit_option (option_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74BF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier ADD CONSTRAINT FK_21691B4F77D927C FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier ADD CONSTRAINT FK_21691B4F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier_option ADD CONSTRAINT FK_E41CE3CF38989DF4 FOREIGN KEY (ligne_panier_id) REFERENCES ligne_panier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ligne_panier_option ADD CONSTRAINT FK_E41CE3CFA7C41D6F FOREIGN KEY (option_id) REFERENCES option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE produit_option ADD CONSTRAINT FK_ADD4CB8AF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit_option ADD CONSTRAINT FK_ADD4CB8AA7C41D6F FOREIGN KEY (option_id) REFERENCES option (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B82EA2E54');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74BF347EFB');
        $this->addSql('ALTER TABLE ligne_panier DROP CONSTRAINT FK_21691B4F77D927C');
        $this->addSql('ALTER TABLE ligne_panier DROP CONSTRAINT FK_21691B4F347EFB');
        $this->addSql('ALTER TABLE ligne_panier_option DROP CONSTRAINT FK_E41CE3CF38989DF4');
        $this->addSql('ALTER TABLE ligne_panier_option DROP CONSTRAINT FK_E41CE3CFA7C41D6F');
        $this->addSql('ALTER TABLE produit DROP CONSTRAINT FK_29A5EC27BCF5E72D');
        $this->addSql('ALTER TABLE produit_option DROP CONSTRAINT FK_ADD4CB8AF347EFB');
        $this->addSql('ALTER TABLE produit_option DROP CONSTRAINT FK_ADD4CB8AA7C41D6F');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE ligne_commande');
        $this->addSql('DROP TABLE ligne_panier');
        $this->addSql('DROP TABLE ligne_panier_option');
        $this->addSql('DROP TABLE option');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE produit_option');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
